vim.g.rustaceanvim = {
    tools = {
        executor = require('rustaceanvim.executors').toggleterm,
        test_executor = require('rustaceanvim.executors').toggleterm,
        float_win_config = { border = "rounded" },
    },
    dap = {
        adapter = function()
            return require("dap").adapters.codelldb
        end
    },
    server = {
        default_settings = {
            ["rust-analyzer"] = {
                files = {
                    exclude = {
                        -- Ignore all files/directories that contain symlinks to the nix store, as that seemingly causes rust-analyzer to scan the entire store:
                        -- https://github.com/rust-lang/rust-analyzer/issues/14734#issuecomment-2373988391
                        ".direnv",
                        "result",
                        "result-dev",
                        "result-man",
                        "result-out",
                    }
                },

                assist = {
                    -- Add `#[must_use]` to functions generated by code actions.
                    emitMustUse = true,
                    -- Use `Self::` instead of the type name in things like generated match arms.
                    preferSelf = true,
                },

                -- Show diagnostics from `cargo clippy` instead of `cargo check`. The former is a bit stricter.
                check = { command = "clippy" },

                -- Don't show diagnostics for inactive cfg directives.
                diagnostics = { disabled = { "inactive-code" } },
            }
        }
    }
}
