name: "Build"
on: [push, pull_request]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: nix build --print-build-logs

      - name: Run checks
        run: nix flake check --print-build-logs --keep-going --all-systems
