name: "Build"
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with: 
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-sandbox-paths = /run/agenix

      # Used to decrypt agenix secrets
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Decrypt secrets used in sandbox
        run: |
          mkdir -p /run/agenix

          AGENIX_REV=$(nix flake metadata --json | jq -r '.locks.nodes.agenix.locked.rev')
          nix shell github:ryantm/agenix/${AGENIX_REV}

          pushd ./secrets

          export EDITOR=cat
          agenix -e ./sm64.age > /run/agenix/sm64-us.z64

          popd

      - name: Check flake
        run: nix flake check

      - name: Build systems
        run: DOTFILES_DIR=$(pwd) nix run .#build --impure
