# Configuration file for sops, see https://github.com/Mic92/sops-nix
keys:
  - &machine-nixos-pc age145ad2emhk7e8759784w0j2aenvxe9uuymtj2xhlshk0qhgcrsgpqadhpvu
  - &machine-nixos-macbook age1xtqd3ncx6d3365t8ee96lwyeq5mx35heexvjxgyrh6yytqspzcjqmj554w
  - &user-ivv age1dg4zwyrvau86mchwky7al8a73lzaqm2d6rf66qe762l5wj3nm96qcwek58
  - &user-ivv-laptop age1zj8jq8vmgv83mcds2x99c5gf2xdnqnahpskpythwl2v9he0u6vdsdww0xw

creation_rules:
  - path_regex: ^.+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *machine-nixos-pc
      - *machine-nixos-macbook
      - *user-ivv
      - *user-ivv-laptop
